# Generated by Django 5.1.3 on 2026-01-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_applied_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
