# Generated by Django 5.1.3 on 2026-01-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.CharField(default='listed', max_length=20),
        ),
    ]
